<a href="https://colab.research.google.com/github/623021002-7/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลายๆตัวไว้ด้วยกันอย่างเป็นระเบียบ

##  ` ` `list() ` ` `
- เก็บอะไรก็ได้
- ลำดับในการเก็บ มีความสำคัญ

In [ ]:
list_a = [1,2,3,4,5,6] #[ ] square brackets

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b = ['ab',2,3.14, list_a]

In [ ]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วย เลขลำดับของ list

In [ ]:
list_a[3]

4

In [ ]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b[3][4]

5

In [ ]:
list_a[6]

IndexError: ignored

In [ ]:
list_a [-1] #index -1 คือตัวสุดของ list

6

In [ ]:
list_a[-4]

3

### การสร้าง ` ` `list()` ` `

In [ ]:
list_x1 = [] #แบบที่ 1
list_x2 = list() #แบบที่ 2

In [ ]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย ` ` `append()` ` `

In [ ]:
list_x1.append(2)

NameError: ignored

In [ ]:
list_x1

NameError: ignored

In [ ]:
list_x1.append(4)
print(list_x1)

NameError: ignored

In [ ]:
list_x1[0]

In [ ]:
list_x1[-1]

In [ ]:
list_x2

In [ ]:
list_x2.append('ha')

In [ ]:
list_x2

### ลบสมาชิกจาก list

In [ ]:
list_x1.append('ha')

In [ ]:
list_x1

[2, 'ha']

In [ ]:
list_x1.pop()

'ha'

In [ ]:
list_x1

[2]

In [ ]:
list_x1.pop()
print(list_x1)

[]


###` ` `len()` ` ` ตรวจสอบจำนวนสมาชิกของ list

In [ ]:
print(list_b)
print(len(list_b))


NameError: ignored

In [ ]:
len(list_a)

### String is a list of characters

In [ ]:
st_stat = 'Department of Statistics, Faculty of science'

In [ ]:
st_stat[10]

' '

In [ ]:
len(st_stst)

NameError: ignored

### List Slicing  ` ` `: ` ` `


In [ ]:
list_a

NameError: ignored

In [ ]:
list_a[2]

NameError: ignored

In [ ]:
list_a[-3:] # : colon

In [ ]:
list_a[1:4]

In [ ]:
list_a[:4]

In [ ]:
list_a[-3:]

In [ ]:
list_a[:]

### step

In [ ]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [ ]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [ ]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### range()

In [ ]:
range(21)

range(0, 21)

In [ ]:
a = list(range(21))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

## HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่่ง split() ช่วย (print ออกมาให้สวยงาม)
- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [ ]:
# 01:00:00
a = 1*60*60
print(a)

3600


In [ ]:
# 01:02:03
a = (1*60*60)+(2*60)+3
print(f'01:02:03 แปลงเป็นวินาที ได้ {a} วินาที')

01:02:03 แปลงเป็นวินาที ได้ 3723 วินาที


In [ ]:
q1 = '12:30:15'
q1_sp = q1.split(':')
print(q1_sp)
answer1=int(q1_sp[0])*3600+int(q1_sp[1])*60+int(q1_sp[2])
print("ตอบ แปลงเป็นวินาที ได้ =",answer1,"วินาที")

['12', '30', '15']
ตอบ แปลงเป็นวินาที ได้ = 45015 วินาที


In [ ]:
q2 = '13:41:07'
q2_sp = q2.split(':')
print(q2_sp)
answer2=int(q2_sp[0])*3600+int(q2_sp[1])*60+int(q2_sp[2])
print("ตอบ แปลงเป็นวินาที ได้ =",answer2,"วินาที")

['13', '41', '07']
ตอบ แปลงเป็นวินาที ได้ = 49267 วินาที


In [ ]:
q3 = '09:11:50'
q3_sp = q3.split(':')
print(q3_sp)
answer3=int(q3_sp[0])*3600+int(q3_sp[1])*60+int(q3_sp[2])
print("ตอบ แปลงเป็นวินาที ได้ =",answer3,"วินาที")

['09', '11', '50']
ตอบ แปลงเป็นวินาที ได้ = 33110 วินาที


In [ ]:
q4 = '21:30:15'
q4_sp = q4.split(':')
print(q4_sp)
answer4=int(q4_sp[0])*3600+int(q4_sp[1])*60+int(q4_sp[2])
print("ตอบ แปลงเป็นวินาที ได้ =",answer4,"วินาที")

['21', '30', '15']
ตอบ แปลงเป็นวินาที ได้ = 77415 วินาที


In [ ]:
q5 = '03:10:15'
q5_sp = q5.split(':')
print(q5_sp)
answer5=int(q5_sp[0])*3600+int(q5_sp[1])*60+int(q5_sp[2])
print("ตอบ แปลงเป็นวินาที ได้ =",answer5,"วินาที")

['03', '10', '15']
ตอบ แปลงเป็นวินาที ได้ = 11415 วินาที


# Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่มีความสำคัญ

### สร้าง Dictionary

In [ ]:
dict_a = {1: 'Happy','N': 'New','2022':'Year'} # { } curly brackets

### การชี้สมาชิกใน Dictionary

In [ ]:
dict_a[1]

'Happy'

In [ ]:
dict_a['N']

'New'

In [ ]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [ ]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

dict_values(['Happy', 'New', 'Year'])

### การเพิ่มสมาชิกลงไปใน Dictionary

In [ ]:
dict_a[7] = 3.14

In [ ]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [ ]:
dict_a['N'] = 'NNNNEEEEWWWW'

In [ ]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEEEEWWWW'}

## Numpy Array

- เก็บได้แต่ตัวเลข
- อ้างอิงโดยใช้ พิกัด (2มิติ ก็มองเป็น Matrix)


In [ ]:
import numpy

### 1D Array

In [5]:
list_A =[1,2,3,4,5]

In [6]:
arr_a = numpy.array(list_A)

NameError: ignored

In [7]:
arr_a

NameError: ignored

In [8]:
list_A

[1, 2, 3, 4, 5]

In [9]:
arr_a[0]

NameError: ignored

In [10]:
list_A[0]

1

In [11]:
5 * arr_a # Matrix (Scalar multiplication)

NameError: ignored

In [12]:
5* list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
arr_b = numpy.array([10,20,30,40,50])

In [ ]:
print(arr_a)

In [ ]:
arr_a + arr_b

### 2D Array

In [ ]:
import numpy as np

In [ ]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2_z.shape

(2, 3)

### `np.zeros()`

In [ ]:
arr_2_3_5_0 = np.zeros((3,5))

In [ ]:
arr_2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr_2_3_5_0[1,2] = 9 # กำหนดค่า

In [ ]:
arr_2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr_2_3_5_0[1,2]

9.0

In [ ]:
print(list_A) # เปลี่ยนค่าใน list()
list_A[-1]='Christmas'
print(list_A)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


### `np.ones()`

In [ ]:
arr_2_4_5_1 = np.ones((4,5))

In [ ]:
arr_2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr_2_4_5_200 = 200*np.ones((4,5))

In [ ]:
arr_2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

## Matrix operations

### การบวก ลบ matrix บวกลบตัวที่อยู่ตำแหน่งเดียวกัน

In [ ]:
arr2_4_5_200 + arr2_3_5_0 #การบวก ลบ matrix shape ต้องเท่ากัน

NameError: ignored

In [ ]:
arr_2_4_5_200 + arr_2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

### การคูณ Matrix
- $aM$ scalar คูณ Matrix (scalar คูณกระจายเข้าไปทุกตัวของ Matrix)
- $M\times N$ Matrix คูณ Matrix (แถวคูณหลัก)

In [ ]:
5* arr_a #Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [ ]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [ ]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [ ]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [ ]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

In [ ]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [ ]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

In [ ]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [ ]:
np.dot(mat_c,mat_b)

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [ ]:
mat_X =np.dot(mat_c,mat_b)

In [ ]:
mat_a * mat_b # คูณด้วยตำแหน่งเดียวกัน


array([[  2,   6,  25],
       [  8,  24, -49]])

### Matrix Slicing

In [ ]:
mat_X[:2,:2]

array([[ 8, 16],
       [16, 32]])

## HW3
1. สร้าง array ที่เป็น ต้น Christmas
2. slice เลข 1 ออกมาจาก array HW3 ด้วยการ slice แค่ครั้งเดียว

In [36]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

1. สร้าง array ที่เป็น ต้น Christmas

In [3]:
import numpy as np

In [29]:
HW = np.ones((23,15))
HW

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [32]:
HW[1:4,7] = 44
HW[2:5,6] = 44
HW[2:5,8] = 44
HW[2:3,5] = 44
HW[2:3,9] = 44
HW[4:17,7] = 66
HW[5:17,6] = 66
HW[5:17,8] = 66
HW[6:17,5] = 66
HW[6:17,9] = 66
HW[7:8,4] = 66
HW[7:8,10] = 66
HW[9:17,4] = 66
HW[9:17,10] = 66
HW[10:11,3] = 66
HW[10:11,11] = 66
HW[12:17,3] = 66
HW[12:17,11] = 66
HW[13:14,2] = 66
HW[12:17,3] = 66
HW[12:17,11] = 66
HW[13:14,2] = 66
HW[13:14,12] = 66
HW[15:17,2] = 66
HW[15:17,12] = 66
HW[16:17,1] = 66
HW[16:17,13] = 66
HW[17:21,7] = 99
HW[17:21,6] = 99
HW[17:21,8] = 99
HW
















array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1., 44.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 44., 44., 44., 44., 44.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., 44., 44., 44.,  1.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., 44., 66., 44.,  1.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., 66., 66., 66.,  1.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 66., 66., 66., 66., 66.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1., 66., 66., 66., 66., 66., 66., 66.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 66., 66., 66., 66., 66.,  1.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1.,  1., 66., 66., 66., 66., 66., 66., 66.,  1.,  1.,
         1.,  1.],
       [ 1.,  1.,  1., 66., 66., 66., 66., 66., 66., 66., 66., 66.,  1.,
       

2. slice เลข 1 ออกมาจาก array HW3 ด้วยการ slice แค่ครั้งเดียว

In [38]:
HW3[::4,2::2] #ตัดโดยเอาทุกหลักโดยนับทีละ 4 step และเอาตั้งแต่แถวที่ 2 ไปโดยนับทีละ 2 step

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Pandas Dataframe (แยกออกไปเป็น Notebook เฉพาะ)